apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations: # <-- קוראים לרובוט התעודות
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: hello.3.211.120.10.nip.io # <-- הדומיין החדש של האפליקציה
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-service
            port:
              number: 80
  tls: # <-- מבקשים לשמור את התעודה בכספת
  - hosts:
    - hello.3.211.120.10.nip.io
    secretName: hello-tls-secret